// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaRopa.Infraestructura.AccesoDatos;

/// <summary>
/// Relaciona los productos que un cliente ha agregado a su carrito, incluyendo la cantidad.
/// </summary>
public partial class CarritoProducto
{
    public int id_carritoproducto { get; set; }

    public int id_carrito { get; set; }

    public int id_producto { get; set; }

    public int cantidad { get; set; }

    public virtual Carrito id_carritoNavigation { get; set; }

    public virtual Producto id_productoNavigation { get; set; }
}