// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaRopa.Infraestructura.AccesoDatos;

/// <summary>
/// Representa el carrito de compras de un cliente, creado antes de confirmar un pedido.
/// </summary>
public partial class Carrito
{
    public int id_carrito { get; set; }

    public int id_usuario { get; set; }

    public DateOnly fecha_creado { get; set; }

    public virtual ICollection<CarritoProducto> CarritoProducto { get; set; } = new List<CarritoProducto>();

    public virtual Usuario id_usuarioNavigation { get; set; }
}