// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaRopa.Infraestructura.AccesoDatos;

/// <summary>
/// Define las categorías generales de productos (ej: Ropa, Calzado, Accesorios).
/// </summary>
public partial class Categoria
{
    public int id_categoria { get; set; }

    public string nombre { get; set; }

    public virtual ICollection<Subcategoria> Subcategoria { get; set; } = new List<Subcategoria>();
}