// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaRopa.Infraestructura.AccesoDatos;

/// <summary>
/// Define la categoría del cliente en base al monto de sus compras (Cobre, Plata u Oro), lo que influye en los descuentos aplicables.
/// </summary>
public partial class ClasificacionCliente
{
    public int id_clasificacioncliente { get; set; }

    public int id_usuario { get; set; }

    public string tipo_cliente { get; set; }

    public virtual Usuario id_usuarioNavigation { get; set; }
}