// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaRopa.Infraestructura.AccesoDatos;

/// <summary>
/// Lista de colores disponibles para los productos (ej: rojo, azul, negro).
/// </summary>
public partial class Color
{
    public int id_color { get; set; }

    public string nombre { get; set; }

    public virtual ICollection<Stock> Stock { get; set; } = new List<Stock>();
}