// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaRopa.Infraestructura.AccesoDatos;

/// <summary>
/// Contiene la información de la factura generada para cada pedido, incluyendo el descuento aplicado y el total final.
/// </summary>
public partial class Factura
{
    public int id_factura { get; set; }

    public int id_pedido { get; set; }

    public decimal? descuento_aplicado { get; set; }

    public decimal? total_final { get; set; }

    public virtual Pedido id_pedidoNavigation { get; set; }
}