// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaRopa.Infraestructura.AccesoDatos;

/// <summary>
/// Registra la actividad de navegación del cliente por el catálogo (productos vistos, frecuencia, etc.).
/// </summary>
public partial class HistorialNavegacion
{
    public int id_historialnavegacion { get; set; }

    public int id_usuario { get; set; }

    public int id_producto { get; set; }

    public DateTime fecha { get; set; }

    public int interacciones { get; set; }

    public virtual Producto id_productoNavigation { get; set; }

    public virtual Usuario id_usuarioNavigation { get; set; }
}