// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaRopa.Infraestructura.AccesoDatos;

/// <summary>
/// Almacena las marcas de los productos (por ejemplo: Nike, Adidas, Zara).
/// </summary>
public partial class Marca
{
    public int id_marca { get; set; }

    public string nombre { get; set; }

    public virtual ICollection<Producto> Producto { get; set; } = new List<Producto>();
}