// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaRopa.Infraestructura.AccesoDatos;

/// <summary>
/// Contiene las diferentes formas de pago disponibles (ej: tarjeta, efectivo, PayPal).
/// </summary>
public partial class MetodoPago
{
    public int id_pago { get; set; }

    public string nombre { get; set; }

    public virtual ICollection<Pedido> Pedido { get; set; } = new List<Pedido>();
}