// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaRopa.Infraestructura.AccesoDatos;

/// <summary>
/// Almacena los pedidos realizados por los clientes, incluyendo fecha, total y método de pago.
/// </summary>
public partial class Pedido
{
    public int id_pedido { get; set; }

    public int id_usuario { get; set; }

    public DateOnly fecha_pedido { get; set; }

    public decimal total { get; set; }

    public int? id_pago { get; set; }

    public virtual ICollection<DetallePedido> DetallePedido { get; set; } = new List<DetallePedido>();

    public virtual ICollection<Factura> Factura { get; set; } = new List<Factura>();

    public virtual MetodoPago id_pagoNavigation { get; set; }

    public virtual Usuario id_usuarioNavigation { get; set; }
}