// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaRopa.Infraestructura.AccesoDatos;

/// <summary>
/// Almacena la calificación (de 1 a 5 estrellas) que un cliente ha dado a un producto
/// </summary>
public partial class PreferenciaProducto
{
    public int id_preferenciaproducto { get; set; }

    public int id_usuario { get; set; }

    public int id_producto { get; set; }

    public int? estrellas { get; set; }

    public virtual Producto id_productoNavigation { get; set; }

    public virtual Usuario id_usuarioNavigation { get; set; }
}