// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaRopa.Infraestructura.AccesoDatos;

/// <summary>
/// Guarda los productos sugeridos a un cliente, junto con la razón de dicha sugerencia (por navegación, compras anteriores, etc.).
/// </summary>
public partial class ProductoSugerido
{
    public int id_productosugerido { get; set; }

    public int id_usuario { get; set; }

    public int id_producto { get; set; }

    public string razon_sugerencia { get; set; }

    public virtual Producto id_productoNavigation { get; set; }

    public virtual Usuario id_usuarioNavigation { get; set; }
}