// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaRopa.Infraestructura.AccesoDatos;

/// <summary>
/// Contiene la información principal de los productos que se venden: nombre, descripción, precio, código, marca, subcategoría.
/// </summary>
public partial class Producto
{
    public int id_producto { get; set; }

    public string codigo { get; set; }

    public string nombre { get; set; }

    public string descripcion { get; set; }

    public decimal precio { get; set; }

    public int? id_marca { get; set; }

    public int? id_subcategoria { get; set; }

    public virtual ICollection<CarritoProducto> CarritoProducto { get; set; } = new List<CarritoProducto>();

    public virtual ICollection<DetallePedido> DetallePedido { get; set; } = new List<DetallePedido>();

    public virtual ICollection<HistorialNavegacion> HistorialNavegacion { get; set; } = new List<HistorialNavegacion>();

    public virtual ICollection<PreferenciaProducto> PreferenciaProducto { get; set; } = new List<PreferenciaProducto>();

    public virtual ICollection<ProductoDescartado> ProductoDescartado { get; set; } = new List<ProductoDescartado>();

    public virtual ICollection<ProductoSugerido> ProductoSugerido { get; set; } = new List<ProductoSugerido>();

    public virtual ICollection<Stock> Stock { get; set; } = new List<Stock>();

    public virtual Marca id_marcaNavigation { get; set; }

    public virtual Subcategoria id_subcategoriaNavigation { get; set; }
}