// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaRopa.Infraestructura.AccesoDatos;

/// <summary>
/// Contiene los diferentes roles disponibles en el sistema, como “Administrador”, “Vendedor” y “Cliente”.
/// </summary>
public partial class Rol
{
    public int id_rol { get; set; }

    public string nombre { get; set; }

    public virtual ICollection<UsuarioRol> UsuarioRol { get; set; } = new List<UsuarioRol>();
}