// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaRopa.Infraestructura.AccesoDatos;

/// <summary>
/// Controla la cantidad disponible de cada combinación de producto, color y talla en el inventario.
/// </summary>
public partial class Stock
{
    public int id_producto { get; set; }

    public int id_color { get; set; }

    public int id_talla { get; set; }

    public int cantidad { get; set; }

    public virtual Color id_colorNavigation { get; set; }

    public virtual Producto id_productoNavigation { get; set; }

    public virtual Talla id_tallaNavigation { get; set; }
}