// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaRopa.Infraestructura.AccesoDatos;

/// <summary>
/// Define las tallas disponibles para los productos (ej: S, M, L, 36, 38).
/// </summary>
public partial class Talla
{
    public int id_talla { get; set; }

    public string descripcion { get; set; }

    public virtual ICollection<Stock> Stock { get; set; } = new List<Stock>();
}