// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaRopa.Infraestructura.AccesoDatos;

/// <summary>
/// Asocia usuarios con uno o más roles (relación N:N), permitiendo definir qué permisos tiene cada usuario.
/// </summary>
public partial class UsuarioRol
{
    public int id_usuariorol { get; set; }

    public int id_usuario { get; set; }

    public int id_rol { get; set; }

    public virtual Rol id_rolNavigation { get; set; }

    public virtual Usuario id_usuarioNavigation { get; set; }
}