// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaRopa.Infraestructura.AccesoDatos;

/// <summary>
/// Almacena los datos personales y de acceso de los usuarios del sistema (administradores, vendedores o clientes).
/// </summary>
public partial class Usuario
{
    public int id_usuario { get; set; }

    public string nombre { get; set; }

    public string correo { get; set; }

    public string contraseña { get; set; }

    public string estado { get; set; }

    public string usuario1 { get; set; }

    public virtual ICollection<Carrito> Carrito { get; set; } = new List<Carrito>();

    public virtual ICollection<ClasificacionCliente> ClasificacionCliente { get; set; } = new List<ClasificacionCliente>();

    public virtual ICollection<HistorialNavegacion> HistorialNavegacion { get; set; } = new List<HistorialNavegacion>();

    public virtual ICollection<Pedido> Pedido { get; set; } = new List<Pedido>();

    public virtual ICollection<PreferenciaProducto> PreferenciaProducto { get; set; } = new List<PreferenciaProducto>();

    public virtual ICollection<ProductoDescartado> ProductoDescartado { get; set; } = new List<ProductoDescartado>();

    public virtual ICollection<ProductoSugerido> ProductoSugerido { get; set; } = new List<ProductoSugerido>();

    public virtual ICollection<UsuarioRol> UsuarioRol { get; set; } = new List<UsuarioRol>();
}